name: shadinlab_one
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  get: ^4.6.5
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0
  connectivity: ^3.0.6
  hive_flutter: ^1.1.0
  dio: ^4.0.6
  http: ^0.13.4
  json_annotation: ^4.0.1
  path_provider: ^2.0.2
  audioplayers: ^1.0.1
  flutter_local_notifications: ^9.7.0
  timezone: ^0.8.0
  firebase_messaging: ^12.0.1
  overlay_support: ^2.0.1
  file_picker: ^5.0.0
  #for auth cation
  flutter_facebook_auth: ^4.4.0+1
  twitter_login: ^4.2.3
  linkedin_login: ^2.2.1
  firebase_auth: ^3.6.1
  google_sign_in: ^5.4.0
  #for mimage cahce
  cached_network_image: ^3.2.1
  #date fromate
  intl: ^0.17.0
  background_fetch: ^1.1.0
  #for background
  flutter_background_service: ^2.1.3
  #image get
  image_picker: ^0.8.5+3
  #progess indicator
  percent_indicator: ^4.2.2

dev_dependencies:
  hive_generator: ^1.1.3
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/songs/
